# Generated by Django 4.1.2 on 2022-10-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0007_changeprofile_remove_post_changeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='changeProfile',
        ),
    ]
